In [146]:
import cv2
import os
import numpy as np

In [147]:
os.path.dirname( os.path.abspath("crack_data"))

'C:\\Users\\ladna\\tensorflow2.0\\smartprocess\\crack_models'

In [154]:
noise_path = "crack_data\\noise\\"
original_path = "crack_data\\original\\"

In [155]:
noise_path += "11.jpg"
img = cv2.imread(noise_path, cv2.IMREAD_GRAYSCALE)

In [156]:
print(img.shape)

(2448, 2448)


In [157]:
img = cv2.resize(img, dsize = (250, 250), interpolation = cv2.INTER_AREA)

In [158]:
print(img.shape)

(250, 250)


In [159]:
cv2.imshow("TEST!!", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
original_path += "1.jpg"
img = cv2.imread(original_path, cv2.IMREAD_GRAYSCALE)

In [66]:
print(img.shape)

(250, 250)


In [67]:
print(img)

[[ 79  97 117 ... 108  95  80]
 [ 51  33  30 ...  57  58  52]
 [ 41  33  30 ...  52  48  33]
 ...
 [113 157 164 ...  50   7  37]
 [153 149 159 ...  46  10  43]
 [128 130 135 ...  52   7  40]]


In [22]:
cv2.imshow("TEST!!", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
type(img)

numpy.ndarray

In [25]:
num_data = 22

noise_path = "crack_data\\noise\\"
original_path = "crack_data\\original\\"

In [38]:
print(type(noise_path))

<class 'str'>


In [39]:
print(dir(noise_path))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [46]:
print(len(noise_path))

17


In [52]:
print(noise_path[len(noise_path) - 1] is '\\')

True


In [28]:
list = os.listdir("crack_data\\noise")

In [29]:
print(list)

['1.jpg', '10.JPG', '11.JPG', '12.JPG', '13.JPG', '14.JPG', '15.JPG', '16.JPG', '17.JPG', '18.JPG', '19.JPG', '2.jpg', '20.JPG', '21.JPG', '22.JPG', '3.jpg', '4.JPG', '5.JPG', '6.JPG', '7.JPG', '8.JPG', '9.JPG']


In [32]:
type(list)

list

In [35]:
list = np.array(list)

In [36]:
print(list.shape)

(22,)


In [37]:
print(list[0])

1.jpg


In [249]:
class DataCollect :
    
    #class collecting data : assert(num_of_noise == num_of_original)
    #should be imported numpy(as np), os, cv2(opencv-python)
    #data_set returned two data set of ndarray 
    
    def __init__ (self, noise_path = "crack_data\\noise\\", original_path = "crack_data\\original\\") :
        self.noise_path = noise_path
        self.original_path = original_path
        
        if(self.noise_path[len(self.noise_path) - 1] != "\\") :
            self.noise_path + "\\"
            
        if(self.original_path[len(self.original_path) - 1] != "\\") :
            self.original_path + "\\"
        
        self.noise_list = np.array(os.listdir(noise_path))
        self.original_list = np.array(os.listdir(original_path))
        
        self.num_of_data = self.noise_list.shape[0]
        
        assert(self.num_of_data == self.original_list.shape[0])
        
        self.status = {"collected" : False, "processed" : False}
        
    def raw_data_set (self) :
        noise_data = []
        original_data = []
        
        for i in range(self.num_of_data) :
            noise_path_tmp = self.noise_path + self.noise_list[i]
            original_path_tmp = self.original_path + self.original_list[i]
            
            noise_tmp = cv2.imread(noise_path_tmp, cv2.IMREAD_GRAYSCALE)
            original_tmp = cv2.imread(original_path_tmp, cv2.IMREAD_GRAYSCALE)
            
            noise_tmp_np = np.array(noise_tmp).astype(np.float32)
            original_tmp_np = np.array(original_tmp).astype(np.float32)
            
            if(noise_tmp_np.shape[0] != 250 or noise_tmp_np.shape[1] != 250) :
                noise_tmp = cv2.resize(noise_tmp, dsize = (250, 250), interpolation = cv2.INTER_AREA)
                noise_tmp_np = np.array(noise_tmp).astype(np.float32)
                
            if(original_tmp_np.shape[0] != 250 or original_tmp_np.shape[1] != 250) :
                original_tmp = cv2.resize(original_tmp, dsize = (250, 250), interpolation = cv2.INTER_AREA)
                original_tmp_np = np.array(original_tmp).astype(np.float32)
                
            noise_tmp = noise_tmp_np.tolist()
            original_tmp = original_tmp_np.tolist()
            
            noise_data.append(noise_tmp)
            original_data.append(original_tmp)
        
        noise_data = np.array(noise_data)
        original_data = np.array(original_data)
        
        self.raw_noise_data = noise_data
        self.raw_original_data = original_data
        
        self.status["collected"] = True
        
        return noise_data, original_data
    
    def preprocessed_set (self) :
        if not self.status["collected"] :
            raw_noise, raw_original = self.raw_data_set()
        else :
            raw_noise = self.raw_noise_data
            raw_original = self.raw_original_data
            
        raw_noise /= 255.
        raw_original /= 255.
        
        processed_noise = np.reshape(raw_noise, newshape = (-1, 250, 250, 1))
        processed_original = np.reshape(raw_original, newshape = (-1, 250, 250, 1))
        
        self.processed_noise = processed_noise
        self.processed_original = processed_original
        
        self.status["processed"] = True
        
        return processed_noise, processed_original
    
    def sample_show (self, sample_num = 0) :
        if(sample_num > self.num_of_data - 1) :
            print("There's no image in {} index" .format(sample_num))
            
            return 0
        
        if not self.status["processed"] :
            self.preprocessed_set()
            
        cv2.imshow("sample_show", self.processed_original[sample_num])
        cv2.waitKey(0)
        cv2.destroyAllWindows() 

In [250]:
data = DataCollect()

In [227]:
dir(data)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'noise_list',
 'noise_path',
 'num_of_data',
 'original_list',
 'original_path',
 'preprocessed_set',
 'raw_data_set',
 'sample_show']

In [228]:
noise, original = data.raw_data_set()

In [229]:
noise.shape

(22, 250, 250)

In [230]:
noise[21].shape # 250 : 0, 11, 15-19 

(250, 250)

In [231]:
print(noise[0].min(axis = 1).min(axis = 0))

0.0


In [232]:
print(noise[3].max(axis = 1).max(axis = 0))

175.0


In [233]:
print(noise[3].max(axis = 0).max(axis = 0))

175.0


In [234]:
print(noise.shape)

(22, 250, 250)


In [235]:
noise = np.reshape(noise, newshape = (-1, 250, 250, 1))

In [236]:
noise.shape

(22, 250, 250, 1)

In [237]:
processed_noise, processed_original = data.preprocessed_set()

In [238]:
processed_noise.shape

(22, 250, 250, 1)

In [239]:
processed_noise[0]

array([[[0.12941176],
        [0.6745098 ],
        [0.72941176],
        ...,
        [0.65882353],
        [0.63529412],
        [0.50588235]],

       [[0.1254902 ],
        [0.67058824],
        [0.7372549 ],
        ...,
        [0.65882353],
        [0.69019608],
        [0.50588235]],

       [[0.07843137],
        [0.65882353],
        [0.75294118],
        ...,
        [0.65490196],
        [0.68627451],
        [0.48627451]],

       ...,

       [[0.59607843],
        [0.56470588],
        [0.57647059],
        ...,
        [0.58431373],
        [0.58039216],
        [0.57254902]],

       [[0.6       ],
        [0.55686275],
        [0.55686275],
        ...,
        [0.58431373],
        [0.57254902],
        [0.57254902]],

       [[0.55294118],
        [0.5254902 ],
        [0.53333333],
        ...,
        [0.58039216],
        [0.57647059],
        [0.57647059]]])

In [251]:
data.sample_show(10)

In [244]:
if not False :
    print("true")

true


In [245]:
dic = {"a" : True, "b" : False}

In [248]:
print(dic["a"])

False


In [247]:
dic["a"] = False